### ISSUE TITLE
Working together on the Grideditor

### ISSUE THREAD

**Issue by onigetoc** [Aris-haryanto/Laravel-5-CRUD#1]
Hi Aris.
Sorry to contact you this way. I love the grideditor and you seem active on this version.
I want to make new drag n drop component and i have done a lot of work but i have lot of bug too. We may work on a new version on Github together.
this what i make so far.
http://scripts.toolurl.com/1-apps/Bootstrap-layout/grid-editor-master-FORK/grid-editor-master-FORK/example/
- Left menu with drop components. (loaded from a json file)
- style changer drop down.
- search filter component
- problem with loadind or not the tinycme editor. It only load when we add row.

Another one from another forked project.
http://scripts.toolurl.com/1-apps/Bootstrap-layout/bootstrap-editor-master%20V3/

You can contact me from this contact form
http://softplug.com/contact-us/

**Comment by Aris-haryanto** [comment]
wow this is good
but you can't add another element inside the grid directly this will be replaced with tinymce function
i've idea for this problem

where can i fork with you , can you give the url

**Comment by onigetoc** [comment]
@Aris-haryanto 
Can you send me a message from the form here.
http://softplug.com/contact-us/
This way i will get your email so we could communicate.

**Comment by onigetoc** [comment]
Please email me.
I did a resize column system. (some bugs)
It snap to Bootstrap column size on resize.
Just resize column with your mouse
http://jsfiddle.net/onigetoc/ag4mgpbs/1/show/

Or a fluid one who snap after leaving the mouse.
http://jsfiddle.net/onigetoc/322fhnL7/17/show/

**Comment by Aris-haryanto** [comment]
Oke Gino, i've sent email to you

**Comment by onigetoc** [comment]
Hi Aris,

I had a hard time to understand the grideditor and i started again
completly on a new one i found on Github.
https://github.com/erickthered/bootstrap-editor


the new one was only 100 lines of code and not bad, but i tryed to add the
grideditor function and a lot of stuff.

Now i hate the drag n drop i did, should be remade from scratch.

I did a system to not use PLUS +  and MINUS -  button to resize the grid
but now it rezise with the mouse and it snap to Bootstrap grid system.
(Only column inside row can do that.)
I created the basic code on jsfiddle.
https://jsfiddle.net/onigetoc/oejoayq5/show/ (You can rezise with the mouse)

I added a code view with codemirror, not perfect, should hide more codes
like the tinymce html.

The ugly black square on left is my grid maker and it work only on drag n
drop, not on click, its ugly now because i have not yet decide how it would
look like.
allmost all html is generated with javascript.

http://scripts.toolurl.com/1-apps/Bootstrap-layout/bootstrap-editor-master%20V3/

We may help each other to make tha basic work and work latter alone on our
own project or do a complete build service toghether.
I have plenty of ideas to make it better than all the Bootstrap layout
builder we found on the net, even better than the Wordpress plugin Composer.

I also find this software to build bootstrap layout, i think it's the best
i found and it look a lot like i want to do but it miss a lot of features
and it's limited.
https://mobirise.com/

Best regard
Gino
Softplug.com

2016-01-20 4:48 GMT-05:00 Aris Haryanto <notifications@github.com>:
